#
#       ::::::::: ::::::::::: ::::    :::  ::::::::
#      :+:    :+:    :+:     :+:+:   :+: :+:    :+:
#     +:+    +:+    +:+     :+:+:+  +:+ +:+
#    +#++:++#+     +#+     +#+ +:+ +#+ :#:
#   +#+           +#+     +#+  +#+#+# +#+   +#+#
#  #+#           #+#     #+#   #+#+# #+#    #+#
# ###       ########### ###    ####  ########
#
# ELK Compose File POC September 2019
# David Monaghan

version '0.1'
services: 
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.name=docker-
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
     memlock:
       soft: -1
       hard: -1
    networks:
      - esnet
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.3.2
    ports:
      - 5044:5044
    environment:
      SERVER_NAME: logstash.local
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    ports:
      - 5601:5601
    networks:
      - esnet
  filebeat:
    container_name: filebeat
    build:
     context: .
     dockerfile: filebeat.Dockerfile
    volumes:
      - ./logs:/var/log
    networks:
      - esnet
networks:
  esnet: